export type { ContainmentRoots, ReleaseRoot, PolicyHash, AuditStateRoot, RevocationStateRoot } from './types/index.js';
export {
  EMPTY_ROOT,
  emptyRoots,
  type AsciiSlug,
  type Sha256Hex,
  type Base64Url,
  type IsoTimestamp,
  type ActionProposal,
  type SanitizedModelTaskPacket,
  type StateEnvelope,
  type MemoryQuotaState,
  OUTPUT_CONTRACT_ACTION_PROPOSAL_V1,
  ACTION_PROPOSAL_ALLOWED_FIELDS,
  STATE_ENVELOPE_VERSION,
} from './types/index.js';

export {
  validateAsciiSlug,
  validateSha256Hex,
  validatePositiveSafeInteger,
  validateNonNegativeSafeInteger,
  validateNoForbiddenFields,
  validateActionProposal,
  validateSanitizedModelTaskPacket,
  validateStateEnvelope,
  FORBIDDEN_CONTROL_PLANE_FIELDS,
  type ValidationResult,
} from './validators/index.js';

export {
  StrictJsonIntake,
  StrictJsonIntakeError,
  type StrictJsonIntakeOptions,
} from './strict-json/index.js';

export {
  type SemanticRuleEvaluation,
  type SemanticValidationResult,
  type PaymentPolicyContext,
  type SemanticPolicyInput,
  type FinalSemanticResult,
  SemanticPolicyEngine,
  evaluateSemanticPolicy,
  mapSemanticResultToPolicyDecision,
  applySemanticResultToEnvelope,
} from './semantic-policy/index.js';

export {
  type TelemetryEventType,
  type TelemetryEventEnvelope,
  type TelemetryEventStatus,
  TELEMETRY_EVENT_TYPES,
  TelemetryEmitter,
  TelemetryJsonlWriter,
  buildTelemetryEvent,
  buildSafePreview,
  verifyHashChain,
  emitPoisonedInvoiceTrace,
  type RedactionProfile,
} from './telemetry/index.js';

export {
  type AuditReceipt,
  type AuditStateRoot as AuditLedgerStateRoot,
  AuditLedger,
  createAuditReceipt,
  EMPTY_AUDIT_ROOT,
  placeholderAuditStateRoot,
} from './audit/index.js';

export {
  type ParameterBoundActionToken,
  type UnsignedParameterBoundActionToken,
  type TokenIssuanceDecision,
  type TokenIssuanceResult,
  type TokenIssuanceRequest,
  type TokenIssuanceBlockedReason,
  TOKEN_TYPE_PARAMETER_BOUND,
  TOKEN_ISSUER,
  DEFAULT_PARAMETER_SCHEMA_VERSION,
  DEFAULT_SIGNING_KEY_ID,
  DEFAULT_TOKEN_TTL_MS,
  TOKEN_ISSUANCE_BLOCKED_REASONS,
  MODEL_FORBIDDEN_TOKEN_FIELDS,
  assertNoModelSuppliedTokenFields,
  buildUnsignedTokenClaims,
  evaluateTokenPolicyGate,
  type TokenPolicyGateResult,
  canonicalizeActionProposal,
  canonicalizeApprovedParameters,
  actionProposalToApprovedParameters,
  ParameterCanonicalizerError,
  type ApprovedExecutionParameters,
  computeParameterHash,
  tryComputeParameterHash,
  MockTokenSigner,
  MOCK_SIGNATURE_PREFIX,
  isMockSignature,
  type TokenSigner,
  generateJti,
  resetJtiSequenceForTests,
  generateIdempotencyKey,
  type IdempotencyKeyInput,
  TokenBroker,
  buildTokenIssuanceTelemetryPayload,
  assertTokenIssuanceTelemetrySafe,
  type TokenIssuanceTelemetryPayload,
  type TokenBrokerOptions,
} from './token-broker/index.js';

export {
  type ToolExecutionDecision,
  type ToolExecutionBlockedReason,
  type ToolExecutionVerificationRequest,
  type ToolExecutionVerificationResult,
  type ToolExecutorVerifierOptions,
  TOOL_EXECUTION_BLOCKED_REASONS,
  buildVerificationResult,
  emptyVerificationFlags,
  type VerificationFlags,
  verifyParameterHash,
  verifyTokenSignature,
  verifyTokenNotExpired,
  verifyTokenSingleUse,
  verifyRevocationEpoch,
  verifyContainmentEpoch,
  verifyKeyEpoch,
  verifyJtiUnused,
  verifyIdempotencyKeyUnused,
  verifyRiskModePermitsExecution,
  verifyToolExecution,
  deriveToolIdFromAction,
  buildToolExecutorVerificationTelemetryPayload,
  assertToolExecutorVerificationTelemetrySafe,
  type ToolExecutorVerificationTelemetryPayload,
} from './tool-executor/index.js';

export {
  type MemoryFirewallDecision,
  type MemoryFirewallBlockedReason,
  type MemoryEvidenceMetadata,
  type MemoryFirewallPolicy,
  type MemoryWriteRequest,
  type MemoryWriteResult,
  type MemoryReadRequest,
  type MemoryReadResult,
  MEMORY_FIREWALL_BLOCKED_REASONS,
  DEFAULT_MEMORY_FIREWALL_POLICY,
  validateMemoryEvidenceMetadata,
  isInertEvidencePayload,
  evaluateMemoryWrite,
  evaluateMemoryRead,
  buildMemoryWriteTelemetryPayload,
  buildMemoryReadTelemetryPayload,
  assertMemoryFirewallTelemetrySafe,
  type MemoryFirewallTelemetryPayload,
} from './memory-firewall/index.js';

export {
  type EgressDecision,
  type EgressBlockedReason,
  type EgressPolicyArtifact,
  type EgressVerificationRequest,
  type EgressVerificationResult,
  EGRESS_BLOCKED_REASONS,
  DEFAULT_EGRESS_POLICY,
  verifyEgress,
  validateEgressSchemaContract,
  detectExfilPatterns,
  buildEgressTelemetryPayload,
  assertEgressTelemetrySafe,
  type EgressTelemetryPayload,
} from './egress-firewall/index.js';

export {
  REVOCATION_BLOCKED_REASONS,
  riskModeForRevocationStatus,
  escalateRiskMode,
  riskModeForRevocationSignal,
  killSwitchActive,
  computeRevocationStateRoot,
  applyRevocationSignal,
  resolveInFlightActionRace,
  isTokenInvalidatedByRevocation,
  evaluateEnvelopeRevocationGate,
  evaluateRevocationSemanticOverride,
  evaluateHeartbeat,
  DEFAULT_MAX_RENEWALS_PER_SESSION,
  buildRevocationTransitionTelemetryPayload,
  buildHeartbeatTelemetryPayload,
  assertRevocationTelemetrySafe,
  type RevocationSignal,
  type RevocationBlockedReason,
  type RevocationTransitionRequest,
  type RevocationTransitionResult,
  type InFlightRaceRequest,
  type InFlightRaceResult,
  type HeartbeatRequest,
  type HeartbeatResult,
  type RevocationTelemetryPayload,
} from './revocation-engine/index.js';

export {
  type ScenarioDefinition,
  type ScenarioRunResult,
  type ScenarioExpected,
  runScenario,
  compareScenarioResult,
  loadReplayEvents,
  SCENARIO_IDS,
  resolvePaymentPolicy,
  envelopeFromScenario,
  proposalFromScenario,
} from './scenario-engine/index.js';
